server:
  port: 8090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
okta:
   oauth2:
      issuer: https://dev-01021554.okta.com/oauth2/default
      audience: api://default
      client-id: 0oag00tx2kbmlLdkg5d7
      client-secret: TaVwqYndVwmC6YQStIxtlaUtR5F_ioLnib_TQOyXFdfR0fpTBIuh2IAXQmHFK3CO
      scopes: openid, profile, email, office_access
      